### PR TITLE
refactoring sp2n

### LINKED ISSUE #5: Unification of Grid/qcd/utils/Sp2n.h and Grid/qcd/utils/SUn.h
Might be possible though it is not that likely. Potentially, at least some functionality is duplicated and we can extract that as free functions or the like? Assess if such introduced coupling is advantageous in the long run.

### LINKED ISSUE #7: Make ProjectOnGroup a template
In Grid/tensors/Tensor_Ta.h, ProjectOnGroup should probably be a template. We need to figure out the consequences and find a nice, least intrusive way to separate out the implementation from the interface. We should keep an eye on how such change affects other parts of the code.

### PR DESCRIPTION
**Pull request by LupoA**
Closes #7 and further contributes to #5

### CODE REVIEW

**Comment by chillenzer** [comment]
Hi,
thanks for your pull request. Could you please make sure that the tests are all running? In trying to verify the same, I have found that that's not the case. In `tests/core` there were two tests that implicitly assumed `Nc==3`. That's definitely not on you, so I pushed a little `#if Nc==3` to get rid of these failures. But there are also tests failing with
```
error: no member named 'iSUnMatrix' in 'Grid::GaugeGroup<2, Grid::GroupName::SU>'
```
which I didn't investigate further.
Best,
Julian
PS: We have put together a brief idea of how a code review should work [here](https://sa2c.github.io/RSE-handbook/docs/how_we_work/code_review/#the-code-to-be-reviewed) if you want to have a look.

**Comment by chillenzer** [comment]
PPS: We should discuss separately if we want to touch something if `tests/core` at all, so we might revert the [`#if Nc==3` commit](https://github.com/LupoA/Grid/pull/19/commits/29586f6b5ee09bc21b61f00230ec16d9b881e83a) in the end again.

**Comment by chillenzer** [comment]
Hi,

I've had another look at your code. Thanks for the hard work. I've only looked at the code from https://github.com/LupoA/Grid/pull/19/commits/371fd123fb5ddf7da5f151e9b2fcb41829b0f7e0 and before because the later code seems to be work in progress (i.e. fails some tests). Is that correct? If you want the first pull request to be accepted soon, I would suggest that you revert the later commits here and move them to a new branch for a second pull request. Alternatively, we can discuss the status here but only accept at the end.

I very much like the new interface of `ProjectOnGaugeGroup`. It's very clean and allows for great unification. Thanks also for fixing the `iSUnMatrix` oversight. Might have been me actually during the introduction of `GaugeGroup`.

First, I have a question: What is the difference between `ProjectOnGaugeGroup` and `ProjectGn`? And why do the `iVector` overloads declare the `grid` variable? There is also a lingering `ProjectSUn` outside of the `GaugeGroup` class. Why is that? Do we need it? Why is that used inside of `ProjectOnGn`?

One general suggestion would be to move all `group_name` function arguments to the last position in

* `LieRandomize`
* `GaussianFundamentalLieAlgebraMatrix`
* `FundamentalLieAlgebraMatrix`
* `projectOnAlgebra`

They are not actually meant to be used and, hence, we should try to make their explicit use as unlikely as possible. In the current form, if someone wants to use the `scale` argument, they necessarily have to give `group_name` explicitly.

The biggest issue I found is that all of the following functions have identical code in `SUn.impl` and `Sp2n.impl`:

* `GaussianFundamentalLieAlgebraMatrix`
* `FundamentalLieAlgebraMatrix`
* `projectOnAlgebra`
* `HotConfiguration`
* `TepidConfiguration`
* `ProjectGn` (after replacing `Umu = ProjectOnGroup(Umu) -> ProjectOnGaugeGroup(Umu)`)

Why were they moved out of `GaugeGroup`?

**Comment by LupoA** [comment]
Hi Julian thanks a lot for the comments.

I have reverted the commit (yet I am curious about which tests were failing, it was running fine for me)

I am also moving the duplicated code from SU-Sp.impl into GaugeGroup. Once this is done, group_name will be no longer an argument of these functions, so there will be no need to move after the other function arguments. Is that correct?

About ProjectGn and ProjectSU3, these are inherited from existing code... we should discuss whether we need them.

**Comment by chillenzer** [comment]
Just for completeness: Things we discussed in the meeting.

Grid/qcd/utils/GaugeGroup.h:
  * 353: remove this line
  * 357: Sure that this doesn't mean `ProjectGn`?
  * Is the whole difference between `ProjectGn` and `ProjectOnGaugeGroup` to
    have determinant == 1 in the end?

Grid/qcd/utils/SUn.impl:
  * 518: remove this line

Grid/qcd/utils/Sp2n.impl:
  * 263: remove this line

To-Do:
  * Discuss names
  * Replace ProjectSUn by `using` statement

**Comment by LupoA** [comment]
Changes have been committed. 
I've checked: ProjectOnGaugeGroup allows for negative determinant while projectGn returns +1

**Comment by chillenzer** [comment]
Okay. Everything seems to be compiling and running except for `tests/solver/Test_mobius_bcg_prec_nosplit.cc` which is currently not our concern. Gonna close this one. Thanks for the good work!

**Pull request merged**
